name: Custom Image CI

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            node_version:
                description: 'Node.js version to build this image with.'
                type: choice
                required: true
                default: '20'
                options:
                    - '20'
            image_name:
                description: 'Tag name of the image to be pushed.'
                type: string
                required: true
                default: 'luoweb/flowai'
            image_name_custom:
                description: 'Tag name of the custom image to be pushed.'
                type: string
                required: true
                default: 'luoweb/flowai-custom'
            tag_version:
                description: 'Tag version of the image to be pushed.'
                type: string
                required: true
                default: 'latest'

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY  || 'quay.io' }}

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
            - name: Checkout
              uses: actions/checkout@v4.1.1
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3.0.0
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3.0.0
              
            - name: Login to Registry ${{ env.DOCKER_REGISTRY }}
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.DOCKER_REGISTRY }}
                  username: ${{ env.DOCKERHUB_USER }}
                  password: ${{ env.DOCKERHUB_TOKEN }}
            - name: Prepare Custom UI
              run: |
                  pwd
                  ls -l 
                  cd ./packages
                  bash -x ./custom.sh
            
            - name: Build and push CustomUI
              uses: docker/build-push-action@v5.3.0
              with:
                  context: .
                  file: ./Dockerfile
                  build-args: |
                      NODE_VERSION=${{github.event.inputs.node_version}}
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKERHUB_USER }}/flowai-custom:${{ steps.date.outputs.date }}
      
            - name: Build and push
              if: ${{github.event.inputs.image_name_custom  == 'luoweb/flowai-custom' }}
              uses: docker/build-push-action@v5.3.0
              with:
                  context: .
                  file: ./docker/Dockerfile
                  build-args: |
                      NODE_VERSION=${{github.event.inputs.node_version}}
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKERHUB_USER }}/flowai:${{ steps.date.outputs.date }}
            